name: App Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./app

jobs:
  build:
    name: Build for Android and iOS
    runs-on: macos-latest
    strategy:
        fail-fast: false
        matrix:
          target: ["apk --debug", "appbundle --debug", "ios --no-codesign"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Start build
        run: flutter build ${{ matrix.target }}