name: Mobile App Test & Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./app

jobs:
  flutter:
    name: Test + Build for Android and iOS
    runs-on: macos-latest
    strategy:
        fail-fast: false
        matrix:
          target: ["apk --debug", "appbundle --debug", "ios --no-codesign"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get
      
      - run: flutter analyze
      - name: Ensure the Dart code is formatted correctly
        run: dart format --set-exit-if-changed .
      - name: Run Flutter unit tests
        run: flutter test

      - name: Start build
        run: flutter build ${{ matrix.target }}