name: Flutter Tests
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true
    
jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # Set up Flutter.
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      # Analyze, check formatting, and run unit tests.
      - run: flutter analyze
      - name: Ensure the Dart code is formatted correctly
        run: dart format --set-exit-if-changed .
      - name: Run Flutter unit tests
        run: flutter test